org: marcobazzani
app: degirodca
service: DeGiroDca

frameworkVersion: '2 || 3'

variablesResolutionMode: 20210326

provider:
  name: aws
  runtime: python3.8
  region: eu-west-1
  lambdaHashingVersion: 20201221
  environment:
    ENVIRONMENT: "degiro-dca-environment"
    APPLICATION: "serverless-degiro-dca-${sls:stage}"
    CONFIGURATION: "degiro-dca-app-profile-${sls:stage}"
    STAGE: ${sls:stage}
  
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "ssm:GetParameter"
            - "appconfig:GetConfiguration"
          Resource: "*"


resources:
  Resources:
    # the application
    DeGiroDcaApplication:
      Type: AWS::AppConfig::Application
      Properties:
        Name: "serverless-degiro-dca-${sls:stage}"
        Description: "Degiro Dollar Cost Averaging."
        Tags:
          - Key: App
            Value: "DeGiroDcaApplication"
          - Key: Stage
            Value: "${sls:stage}"
    # the application environment
    DeGiroDcaEnvironment:
      Type: AWS::AppConfig::Environment
      Properties:
        ApplicationId: !Ref DeGiroDcaApplication
        Name: "degiro-dca-environment"
        Description: "DeGiro Dca Environment"
        Tags:
          - Key: App
            Value: "DeGiroDcaApplication"
          - Key: Stage
            Value: "${sls:stage}"
    # configuration profile
    DeGiroDcaAppConfigProfile:
      Type: AWS::AppConfig::ConfigurationProfile
      Properties:
        ApplicationId: !Ref DeGiroDcaApplication
        Name: "degiro-dca-app-profile-${sls:stage}"
        LocationUri: "hosted"
    # configuration
    DeGiroDcaConfigurationVersion:
      Type: AWS::AppConfig::HostedConfigurationVersion
      Properties:
        ApplicationId: !Ref DeGiroDcaApplication
        ConfigurationProfileId: !Ref DeGiroDcaAppConfigProfile
        Description: "DeGiro Dca Application Config"
        Content: !Sub |
            {   
                "amount":5000,
                "ETF":[
                    {"id":"4622755", "percentile":"33.0"},
                    {"id":"4622784", "percentile":"33.0"},
                    {"id":"4622969", "percentile":"34.0"}
                ]
            }
        ContentType: "application/json"
        LatestVersionNumber: 1
    # deployment strategy
    DeploymentStrategy:
      Type: AWS::AppConfig::DeploymentStrategy
      Properties:
        Name: "deployment-strategy-${sls:stage}"
        Description: "DeGiro Dca deployment strategy ${sls:stage}"
        DeploymentDurationInMinutes: 0
        FinalBakeTimeInMinutes: 0
        GrowthFactor: 100
        GrowthType: LINEAR
        ReplicateTo: NONE
        Tags:
          - Key: App
            Value: "DeGiroDcaApplication"
          - Key: Stage
            Value: "${sls:stage}"
    # deployment
    DeGiroDcaDeployment:
      Type: AWS::AppConfig::Deployment
      Properties:
        ApplicationId: !Ref DeGiroDcaApplication
        EnvironmentId: !Ref DeGiroDcaEnvironment
        DeploymentStrategyId: !Ref DeploymentStrategy
        ConfigurationProfileId: !Ref DeGiroDcaAppConfigProfile
        ConfigurationVersion: "1"
        Description: "degiro dca deployment ${sls:stage}"
        Tags:
          - Key: App
            Value: "DeGiroDcaApplication"
          - Key: Stage
            Value: "${sls:stage}"


functions:
  degirodca:
    handler: handler.run
    events:
      # Invoke Lambda function every 2nd minute from Mon-Fri
      - schedule: cron(0 12 ? * 2L *)


plugins:
  - serverless-offline
  - serverless-python-requirements
custom:
  pythonRequirements:
    zip: false
    # useDownloadCache: true
    # useStaticCache: true
    invalidateCaches: true
    dockerizePip: non-linux
